language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run prettier:check
  - npm run flow
  - npm test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
