export const testId = {
  // APP
  APP__WRAPPER: "APP__WRAPPER",
  APP__LOADER: "APP__LOADER",

  // PAGE
  PAGE_WRAPPER: "PAGE_WRAPPER",
  PAGE_LOADER: "PAGE_LOADER",

  // HEADER
  HEADER__PANEL: "HEADER__PANEL",
  HEADER__SEARCH_BUTTON: "HEADER__SEARCH_BUTTON",
  HEADER__NAVIGATION_BUTTON: "HEADER__NAVIGATION_BUTTON",

  // PLAYER_NAVIGATION
  PLAYER_NAVIGATION__POPUP: "PLAYER_NAVIGATION__POPUP",
  PLAYER_NAVIGATION__LATEST_ALBUMS_LINK:
    "PLAYER_NAVIGATION__LATEST_ALBUMS_LINK",
  PLAYER_NAVIGATION__SEARCH_ALBUMS_LINK:
    "PLAYER_NAVIGATION__SEARCH_ALBUMS_LINK",
  PLAYER_NAVIGATION__SHARE_ALBUM_LINK: "PLAYER_NAVIGATION__SHARE_ALBUM_LINK",

  // SEARCH_BAR

  SEARCH_BAR__INPUT: "SEARCH_BAR__INPUT",
  SEARCH_BAR__FORM: "SEARCH_BAR__FORM",
  SEARCH_BAR__CLEAR_BUTTON: "SEARCH_BAR__CLEAR_BUTTON",

  // LATEST_ALBUMS_PAGE
  LATEST_LABUMS_PAGE__FALLBACK: "LATEST_LABUMS_PAGE__FALLBACK",
  LATEST_LABUMS_PAGE__FEED: "LATEST_LABUMS_PAGE__FEED",
  LATEST_LABUMS_PAGE__LOAD_MORE_BUTTON: "LATEST_LABUMS_PAGE__LOAD_MORE_BUTTON",
  LATEST_LABUMS_PAGE__FEED_LOADER: "LATEST_LABUMS_PAGE__FEED_LOADER",

  // SEARCH_QUERY_PAGE
  SEARCH_ALBUMS_PAGE__TITLE: "SEARCH_ALBUMS_PAGE__TITLE",
  SEARCH_ALBUMS_PAGE__SUB_TITLE: "SEARCH_ALBUMS_PAGE__SUB_TITLE",
  SEARCH_ALBUMS_PAGE__LOADER: "SEARCH_ALBUMS_PAGE__LOADER",
  SEARCH_ALBUMS_PAGE__FEED: "SEARCH_ALBUMS_PAGE__FEED",
  SEARCH_ALBUMS_PAGE__SAVE_SEARCH_BUTTON:
    "SEARCH_ALBUMS_PAGE__SAVE_SEARCH_BUTTON",
  SEARCH_ALBUMS_PAGE__DELETE_SEARCH_BUTTON:
    "SEARCH_ALBUMS_PAGE__DELETE_SEARCH_BUTTON",
  SEARCH_ALBUMS_PAGE__NEW_RESULTS_BUTTON:
    "SEARCH_ALBUMS_PAGE__NEW_RESULTS_BUTTON",
  SEARCH_ALBUMS_PAGE__FALLBACK_BUTTON: "SEARCH_ALBUMS_PAGE__FALLBACK_BUTTON",

  // FEED_ALBUM
  FEED_ALBUM_WRAPPER: "FEED_ALBUM_WRAPPER",

  // SHARE_ALBUM

  SHARE_ALBUM_PAGE__LOADER: "SHARE_ALBUM_PAGE__LOADER",
  SHARE_ALBUM_PAGE__DROP_ZONE_INPUT: "SHARE_ALBUM_PAGE__DROP_ZONE_INPUT",
  SHARE_ALBUM_PAGE__DROP_ZONE_TEXT: "SHARE_ALBUM_PAGE__DROP_ZONE_TEXT",
  SHARE_ALBUM_PAGE__ALBUM_EDITOR: "SHARE_ALBUM_PAGE__ALBUM_EDITOR",

  // ALBUM EDITOR

  ALBUM_EDITOR__TITLE_INPUT: "ALBUM_EDITOR__TITLE_INPUT",
  ALBUM_EDITOR__SUBMIT_BUTTON: "ALBUM_EDITOR__SUBMIT_BUTTON",
  ALBUM_EDITOR__CANCEL_BUTTON: "ALBUM_EDITOR__CANCEL_BUTTON",

  // ALBUM TRACK EDITOR

  ALBUM_TRACK_EDITOR__WRAPPER: "ALBUM_TRACK_EDITOR__WRAPPER",
  ALBUM_TRACK_EDITOR__TITLE_INPUT: "ALBUM_TRACK_EDITOR__TITLE_INPUT",
  ALBUM_TRACK_EDITOR__TITLE_VALIDATION: "ALBUM_TRACK_EDITOR__TITLE_VALIDATION",
  ALBUM_TRACK_EDITOR__REMOVE_BUTTON: "ALBUM_TRACK_EDITOR__REMOVE_BUTTON",

  // ALBUM ARTIST EDITOR

  ALBUM_ARTIST_EDITOR__ARTIST_NAME_INPUT:
    "ALBUM_ARTIST_EDITOR__ARTIST_NAME_INPUT",
  ALBUM_ARTIST_EDITOR__ARTIST_NAME_VALIDATION:
    "ALBUM_ARTIST_EDITOR__ARTIST_NAME_VALIDATION",

  // ALBUM TRACKLIST

  ALBUM_TRACKLIST__VALIDATION: "ALBUM_TRACKLIST__VALIDATION",
  ALBUM_TRACKLIST__TRACK_INPUT: "ALBUM_TRACKLIST__TRACK_INPUT"
};
