// @flow strict

export const testId = {
  // APP
  APP__WRAPPER: "APP__WRAPPER",
  APP__LOADER: "APP__LOADER",

  // PAGE
  PAGE_WRAPPER: "PAGE_WRAPPER",
  PAGE_LOADER: "PAGE_LOADER",

  // HEADER
  HEADER__PANEL: "HEADER__PANEL",
  HEADER__SEARCH_BUTTON: "HEADER__SEARCH_BUTTON",
  HEADER__NAVIGATION_BUTTON: "HEADER__NAVIGATION_BUTTON",

  // PLAYER_NAVIGATION
  PLAYER_NAVIGATION__POPUP: "PLAYER_NAVIGATION__POPUP",
  PLAYER_NAVIGATION__LATEST_ALBUMS_LINK:
    "PLAYER_NAVIGATION__LATEST_ALBUMS_LINK",
  PLAYER_NAVIGATION__SEARCH_ALBUMS_LINK:
    "PLAYER_NAVIGATION__SEARCH_ALBUMS_LINK",
  PLAYER_NAVIGATION__SHARE_ALBUM_LINK: "PLAYER_NAVIGATION__SHARE_ALBUM_LINK",

  // SEARCH_BAR

  SEARCH_BAR__INPUT: "SEARCH_BAR__INPUT",
  SEARCH_BAR__FORM: "SEARCH_BAR__FORM",
  SEARCH_BAR__CLEAR_BUTTON: "SEARCH_BAR__CLEAR_BUTTON",

  // LATEST_ALBUMS_PAGE
  LATEST_LABUMS_PAGE__FALLBACK: "LATEST_LABUMS_PAGE__FALLBACK",
  LATEST_LABUMS_PAGE__FEED: "LATEST_LABUMS_PAGE__FEED",
  LATEST_LABUMS_PAGE__LOAD_MORE_BUTTON: "LATEST_LABUMS_PAGE__LOAD_MORE_BUTTON",
  LATEST_LABUMS_PAGE__FEED_LOADER: "LATEST_LABUMS_PAGE__FEED_LOADER",

  // SEARCH_QUERY_PAGE
  SEARCH_QUERY_PAGE__TITLE: "SEARCH_QUERY_PAGE__TITLE",
  SEARCH_QUERY_PAGE__LOADER: "SEARCH_QUERY_PAGE__LOADER",
  SEARCH_QUERY_PAGE__FALLBACK: "SEARCH_QUERY_PAGE__FALLBACK",
  SEARCH_QUERY_PAGE__FEED: "SEARCH_QUERY_PAGE__FEED",
  SEARCH_QUERY_PAGE__SAVE_SEARCH_BUTTON:
    "SEARCH_QUERY_PAGE__SAVE_SEARCH_BUTTON",
  SEARCH_QUERY_PAGE__DELETE_SEARCH_BUTTON:
    "SEARCH_QUERY_PAGE__DELETE_SEARCH_BUTTON",
  SEARCH_QUERY_PAGE__NEW_RESULTS_BUTTON:
    "SEARCH_QUERY_PAGE__NEW_RESULTS_BUTTON",

  // SEARCH_QUERIES_PAGE
  SEARCH_QUERIES_PAGE__LOAD_MORE_BUTTON:
    "SEARCH_QUERIES_PAGE__LOAD_MORE_BUTTON",
  SEARCH_QUERIES_PAGE__LOADER: "SEARCH_QUERIES_PAGE__LOADER",
  SEARCH_QUERIES_PAGE__FALLBACK: "SEARCH_QUERIES_PAGE__FALLBACK",
  SEARCH_QUERIES_PAGE__FEED: "SEARCH_QUERIES_PAGE__FEED",

  // SEARCH_QUERY_ITEM
  SEARCH_QUERY_ITEM__WRAPPER: "SEARCH_QUERY_ITEM__WRAPPER",
  SEARCH_QUERY_ITEM__LINK: "SEARCH_QUERY_ITEM__LINK",
  SEARCH_QUERY_ITEM__BUTTON: "SEARCH_QUERY_ITEM__BUTTON",
  SEARCH_QUERY_ITEM__LOADER: "SEARCH_QUERY_ITEM__LOADER",

  // FEED_ALBUM
  FEED_ALBUM_WRAPPER: "FEED_ALBUM_WRAPPER",

  // SEARCH_QUERY_ALBUM
  SEARCH_QUERY_ALBUM__ROOT_WRAPPER: "SEARCH_QUERY_ALBUM__ROOT_WRAPPER"
};
