// @flow strict

export const testId = {
  // PAGE
  PAGE_WRAPPER: "PAGE_WRAPPER",
  PAGE_LOADER: "PAGE_LOADER",

  // SEARCH_QUERY_PAGE
  SEARCH_QUERY_PAGE__TITLE: "SEARCH_QUERY_PAGE__TITLE",
  SEARCH_QUERY_PAGE__LOADER: "SEARCH_QUERY_PAGE__LOADER",
  SEARCH_QUERY_PAGE__FALLBACK: "SEARCH_QUERY_PAGE__FALLBACK",
  SEARCH_QUERY_PAGE__FEED: "SEARCH_QUERY_PAGE__FEED",
  SEARCH_QUERY_PAGE__SAVE_SEARCH_BUTTON:
    "SEARCH_QUERY_PAGE__SAVE_SEARCH_BUTTON",
  SEARCH_QUERY_PAGE__DELETE_SEARCH_BUTTON:
    "SEARCH_QUERY_PAGE__DELETE_SEARCH_BUTTON",
  SEARCH_QUERY_PAGE__NEW_RESULTS_BUTTON:
    "SEARCH_QUERY_PAGE__NEW_RESULTS_BUTTON",

  // SEARCH_QUERIES_PAGE
  SEARCH_QUERIES_PAGE__LOAD_MORE_BUTTON:
    "SEARCH_QUERIES_PAGE__LOAD_MORE_BUTTON",
  SEARCH_QUERIES_PAGE__LOADER: "SEARCH_QUERIES_PAGE__LOADER",
  SEARCH_QUERIES_PAGE__FALLBACK: "SEARCH_QUERIES_PAGE__FALLBACK",
  SEARCH_QUERIES_PAGE__FEED: "SEARCH_QUERIES_PAGE__FEED",

  // SEARCH_QUERY_ITEM
  SEARCH_QUERY_ITEM__WRAPPER: "SEARCH_QUERY_ITEM__WRAPPER",
  SEARCH_QUERY_ITEM__LINK: "SEARCH_QUERY_ITEM__LINK",
  SEARCH_QUERY_ITEM__BUTTON: "SEARCH_QUERY_ITEM__BUTTON",
  SEARCH_QUERY_ITEM__LOADER: "SEARCH_QUERY_ITEM__LOADER",

  // FEED_ALBUM
  FEED_ALBUM_WRAPPER: "FEED_ALBUM_WRAPPER",

  // SEARCH_QUERY_ALBUM
  SEARCH_QUERY_ALBUM__ROOT_WRAPPER: "SEARCH_QUERY_ALBUM__ROOT_WRAPPER"
};
